### ISSUE TITLE
Feature request: Automatically star the account aidenybai

### ISSUE THREAD

**Issue by aidenybai** [willdoescode/star-it-all#1]
Hello sir or madam willdoescode

I believe it would be beneficial if you built in functionality to automatically star the account @aidenybai

As a result of this, I believe that systemic racism and gender equality will be able to be solved

Have a good day

**Comment by KaiDevrim** [comment]
I can make a PR

**Comment by willdoescode** [comment]
Feel free to use Kai's fork.
