### ISSUE TITLE
what

### ISSUE THREAD

**Issue by ghost** [willdoescode/star-it-all#3]
`Updating crates.io index
  Installing star-it-all v0.1.5
   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.69
   Compiling winapi v0.3.9
   Compiling autocfg v1.0.1
   Compiling memchr v2.3.4
   Compiling cfg-if v1.0.0
   Compiling pin-project-lite v0.2.6
   Compiling log v0.4.14
   Compiling libc v0.2.93
   Compiling lazy_static v1.4.0
   Compiling proc-macro-hack v0.5.19
   Compiling ntapi v0.3.6
   Compiling bytes v1.0.1
   Compiling futures-sink v0.3.14
   Compiling proc-macro-nested v0.1.7
   Compiling futures-core v0.3.14
   Compiling version_check v0.9.3
   Compiling itoa v0.4.7
   Compiling futures-task v0.3.14
   Compiling futures-io v0.3.14
   Compiling pin-utils v0.1.0
   Compiling slab v0.4.3
   Compiling serde_derive v1.0.125
   Compiling matches v0.1.8
   Compiling hashbrown v0.9.1
   Compiling fnv v1.0.7
   Compiling native-tls v0.2.7
   Compiling tinyvec_macros v0.1.0
   Compiling httparse v1.4.0
   Compiling serde v1.0.125
   Compiling ryu v1.0.5
   Compiling try-lock v0.2.3
   Compiling percent-encoding v2.1.0
   Compiling httpdate v0.3.2
   Compiling bitflags v1.2.1
   Compiling unicode-segmentation v1.7.1
   Compiling tower-service v0.3.1
   Compiling serde_json v1.0.64
   Compiling encoding_rs v0.8.28
   Compiling anyhow v1.0.40
   Compiling unicode-width v0.1.8
   Compiling vec_map v0.8.2
   Compiling base64 v0.13.0
   Compiling os_str_bytes v2.4.0
   Compiling ipnet v2.3.0
   Compiling mime v0.3.16
   Compiling numtoa v0.1.0
   Compiling strsim v0.10.0
   Compiling tracing-core v0.1.17
   Compiling tokio v1.5.0
   Compiling indexmap v1.6.2
   Compiling futures-channel v0.3.14
   Compiling unicode-bidi v0.3.5
   Compiling http v0.2.4
   Compiling tinyvec v1.2.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling form_urlencoded v1.0.1
   Compiling textwrap v0.12.1
   Compiling heck v0.3.2
   Compiling tracing v0.1.25
   Compiling unicode-normalization v0.1.17
   Compiling want v0.3.0
   Compiling num_cpus v1.13.0
   Compiling termion v1.5.6
   Compiling http-body v0.4.1
error[E0433]: failed to resolve: unresolved import
  --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\lib.rs:24:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^
   |         |
   |         unresolved import
   |         help: a similar path exists: `color::env::sys`

error[E0433]: failed to resolve: unresolved import
  --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\lib.rs:27:9
   |
27 | pub use sys::tty::{is_tty, get_tty};
   |         ^^^
   |         |
   |         unresolved import
   |         help: a similar path exists: `color::env::sys`

error[E0433]: failed to resolve: unresolved import
 --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:5:5
  |
5 | use sys::tty::get_tty;
  |     ^^^
  |     |
  |     unresolved import
  |     help: a similar path exists: `color::env::sys`

error[E0433]: failed to resolve: unresolved import
  --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:28:5
   |
28 | use sys::attr::{get_terminal_attr, raw_terminal_attr, set_terminal_attr};
   |     ^^^
   |     |
   |     unresolved import
   |     help: a similar path exists: `color::env::sys`

error[E0432]: unresolved import `sys`
  --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:29:5
   |
29 | use sys::Termios;
   |     ^^^
   |     |
   |     unresolved import
   |     help: a similar path exists: `color::env::sys`

   Compiling quote v1.0.9
error[E0425]: cannot find function `get_tty` in this scope
  --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:14:36
   |
14 |     thread::spawn(move || for i in get_tty().unwrap().bytes() {
   |                                    ^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_tty` in this scope
  --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:43:36
   |
43 |     thread::spawn(move || for i in get_tty().unwrap().bytes() {
   |                                    ^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
  --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:45:9
   |
45 |         set_terminal_attr(&self.prev_ios).unwrap();
   |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_terminal_attr` in this scope
   --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:102:23
    |
102 |         let mut ios = get_terminal_attr()?;
    |                       ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `raw_terminal_attr` in this scope
   --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:105:9
    |
105 |         raw_terminal_attr(&mut ios);
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
   --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:107:9
    |
107 |         set_terminal_attr(&ios)?;
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
   --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:119:9
    |
119 |         set_terminal_attr(&self.prev_ios)?;
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_terminal_attr` in this scope
   --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:125:23
    |
125 |         let mut ios = get_terminal_attr()?;
    |                       ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `raw_terminal_attr` in this scope
   --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:126:9
    |
126 |         raw_terminal_attr(&mut ios);
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
   --> C:\Users\hstev\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:127:9
    |
127 |         set_terminal_attr(&ios)?;
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to 15 previous errors

Some errors have detailed explanations: E0425, E0432, E0433.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `termion`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `star-it-all v0.1.5`, intermediate artifacts can be found at `C:\Users\hstev\AppData\Local\Temp\cargo-install9BGGpn`

Caused by:
  build failed`

will why isn't it working i want to star all your repos pls man

**Comment by willdoescode** [comment]
looks like termion is not supported on windows, ill look for another colorful output library

**Comment by ghost** [comment]
yay ty

**Comment by willdoescode** [comment]
Should be fixed as of [this commit](https://github.com/willdoescode/star-it-all/commit/0d1546e563df600ecaedfb1e9ff6c7fbbf20dc5d)
